name: Reuseable Workflow
on:
  workflow_call:

jobs:
  deploy-reuse:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy reuseable job
        run: echo "Deploying and Uploading on server ..."
